server.port: 8081

spring:
  datasource:
    url: jdbc:postgresql://192.168.0.102:5432/slotmachine
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

jwksuri: http://auth/oauth2/jwks

startCount: 120
endCount: -45
resultRequestTimeout: -30
drawCloseTime: 10

spring.mvc.async.request-timeout: -1

#account URL
addURL: http://accounts/ticket/add
ticketErrorURL: http://localhost:7070/ticket/error
balanceURL: http://accounts/account/balance
redeemClaimURL: http://accounts/claims

#auth URL
tokenuri: http://auth/oauth2/token

#client URL
clienturi: http://192.168.1.13:3006